package fr.formation.inti.entities;
// Generated 9 ao�t 2019 15:28:43 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StudentRecord generated by hbm2java
 */
@Entity
@Table(name = "studentRecord", catalog = "students")
public class StudentRecord implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer studentId;
	private String studentName;
	private String studentEmail;
	private String studentPassword;
	private String studentGender;
	private String studentAddress;

	public StudentRecord() {
	}

	public StudentRecord(String studentName, String studentEmail, String studentPassword, String studentGender,
			String studentAddress) {
		this.studentName = studentName;
		this.studentEmail = studentEmail;
		this.studentPassword = studentPassword;
		this.studentGender = studentGender;
		this.studentAddress = studentAddress;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "student_id", unique = true, nullable = false)
	public Integer getStudentId() {
		return this.studentId;
	}

	public void setStudentId(Integer studentId) {
		this.studentId = studentId;
	}

	@Column(name = "student_name", length = 100)
	public String getStudentName() {
		return this.studentName;
	}

	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}

	@Column(name = "student_email", length = 50)
	public String getStudentEmail() {
		return this.studentEmail;
	}

	public void setStudentEmail(String studentEmail) {
		this.studentEmail = studentEmail;
	}

	@Column(name = "student_password", length = 20)
	public String getStudentPassword() {
		return this.studentPassword;
	}

	public void setStudentPassword(String studentPassword) {
		this.studentPassword = studentPassword;
	}

	@Column(name = "student_gender", length = 1)
	public String getStudentGender() {
		return this.studentGender;
	}

	public void setStudentGender(String studentGender) {
		this.studentGender = studentGender;
	}

	@Column(name = "student_address", length = 100)
	public String getStudentAddress() {
		return this.studentAddress;
	}

	public void setStudentAddress(String studentAddress) {
		this.studentAddress = studentAddress;
	}

}
